apiVersion: v2
name: cloud-app
description: Cloud-native microservices application with Istio service mesh
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  
  - name: redis
    version: 18.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

keywords:
  - microservices
  - istio
  - clean-architecture
  - fastapi
  - react

maintainers:
  - name: Cloud App Team