repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format

# MyPy disabled due to hyphenated package names causing import issues
# Run manually with: mypy --explicit-package-bases apps/
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.13.0
#   hooks:
#     - id: mypy
#       args: [--explicit-package-bases]
#       additional_dependencies:
#         - types-redis
#         - types-requests
#         - "boto3-stubs[essential]"
#         - types-PyJWT
#         - pydantic
#       exclude: ^tests/|^scripts/

- repo: https://github.com/seddonym/import-linter
  rev: v2.0
  hooks:
    - id: import-linter